# Generated by Django 4.0.5 on 2022-06-04 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_alter_endereco_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
